### ISSUE TITLE
Segmentation Fault in ParaView Lite with .vtp File Upload

### ISSUE THREAD

**Issue by PierreLouis94** [Kitware/paraview-lite#16]
### High-level description
Attempting to upload a .vtp file into ParaView Lite results in a segmentation fault, whereas the same file loads without issue in ParaView Glance. Both ParaView Lite and ParaView Glance are built on the ParaView framework, but they are exhibiting different behaviors with the same file. This discrepancy suggests a potential bug or compatibility issue in ParaView Lite.

### Detailed behavior
error: exception occurred: Segmentation fault

### Expected behavior
Both paraview lite and glance to work the same.

### Environment
- **ParaView Lite**: v1.5.1
- **OS**: Ubuntu 24.04 LTS
- **Browser**: Firefox 125.0.2 (64-bit)

**Comment by jourdain** [comment]
ParaView Lite rely on ParaView (C++) while Glance is 100% JavaScript. Did you try to load your file with ParaView?

**Comment by PierreLouis94** [comment]
Thank you for your suggestion. I tried loading the .vtp file with the full version of ParaView, and it indeed seems to crash there as well. While I haven't seen specific error messages, the behavior aligns with what one might expect from a segmentation fault, similar to what occurs in ParaView Lite. Do you have any Suggestions on how i should approach this issue?

**Comment by jourdain** [comment]
Report something on ParaView directly.
