### ISSUE TITLE
Connection Error and missing dist directory

### ISSUE THREAD

**Issue by PierreLouis94** [Kitware/paraview-lite#17]
I cloned the repository and installed dependencies successfully using the following commands:

$ git clone https://github.com/Kitware/paraview-lite.git
$ cd paraview-lite/
$ npm install

Initially, I encountered numerous errors, but managed to resolve them using npm audit fix. Now, when I run:

$ npm run server

A window appears stating that the application compiled successfully in XXXXms. It indicates that the app is running at both the local and network IP addresses.

Upon accessing the local IP in my browser, I can see the ParaView Lite homepage. However, attempts to connect to it fail, resulting in a connection error.

Additionally, the documentation mentions that running $ npm run serve should build a development version inside the ./dist directory. However, there is no dist directory present in my ParaView Lite repository.

### Environment
- **ParaView Lite**: v1.5.1
- **OS**: Ubuntu 24.04 LTS
- **Browser**: Firefox 125.0.2 (64-bit)

**Comment by jourdain** [comment]
You forgot to build the code with `npm run build`

**Comment by jourdain** [comment]
Also make sure you start the server too.

**Comment by PierreLouis94** [comment]
Hello Sebastien, so I forgot to mention that I ran the build but it was still giving me error messages. Downgrading my node.js version to 16 fixed it for me. Before when it didnt worked i used the most actual (v20.15.0). Thank you
